.github/workflows/docs.yml
.github/workflows/test.yml

Reading the action results is a bit nicer and fixes a few things. I'll leave a comment on specific fixes.

chore: clean up workflows

---

apps/demo/app_15/README.md
apps/demo/app_15/[foo]/[bar].js
apps/demo/app_15/[foo]/[bar]/index.js
apps/demo/app_15/[foo]/index.js
packages/expo-router/src/fork/__tests__/getStateFromPath.test.node.ts
packages/expo-router/src/fork/getStateFromPath.ts

- resolve #15 
- Surface all dynamic params to every route that matches a given URL

feat: surface all nested params to each screen

---

packages/expo-router/babel.js

When bundling with React Native CLI (building from Xcode or Android Studio) the required environment variables will not be set up. This change will attempt to define them based on the babel environment as a fallback.

fix: attempt to define the project root in babel when not defined

---

docs/docs/features/layouts.md

We're going to be dropping Drawer and Stack so we should document how to add them back.

add docs for creating layout components

---

docs/docs/guides/modals.md

- Removed some extra imports
- Added import for missed StatusBar in modal.js snippet

Updated docs for Modals guide

---

docs/docs/intro.md
package.json
packages/expo-router/package.json
yarn.lock

chore: bump metro across repo

---

docs/docs/guides/params.md

Hi! I played around with this library and fell in love with it already! This is a PR for the [docs issue](https://github.com/expo/router/issues/92) I reported earlier. This is simply about updating the example of [param page](https://expo.github.io/router/docs/guides/params) to catch up to the latest API's property.

docs: update example of param page

---

packages/expo-router/src/__tests__/getLinkingConfig.test.node.ts
packages/expo-router/src/__tests__/getRoutes.test.node.ts
packages/expo-router/src/getRoutes.ts
packages/expo-router/src/views/Directory.tsx
packages/expo-router/src/views/Unmatched.tsx

Change this to a more reasonable default and restyle to account for the root layout not being a native stack anymore.

feat!: change __index to _sitemap

---

packages/expo-router/src/getRoutes.ts
packages/expo-router/src/views/Sitemap.tsx

- fix https://github.com/expo/router/issues/104
- resolve formatting issues
- Run every where.
- Ensure scrolling works.
- Ensure nested routes without layout routes work.

fix: sitemap scrolling

---

packages/expo-router/package.json
yarn.lock

Optional imports don't actually work in Metro.

fix: make splash non-optional

---

README.md

Switch alpha to beta to match the description of the repo
Change the word
If it is really beta, then this should be fine.
If not, then the repo description should be updated.

Switch alpha to beta

---

docs/docusaurus.config.js

Make it possible to search the docs

add algolia search to docs

---

README.md

For users to be able to find further examples of using `expo-router` while learning
Added a section in the readme
Clicked the links, made sure they worked

Add examples section to readme

---

packages/expo-router/src/views/Unmatched.tsx

This was the original intent behind showing a URL.

Make the 404 URL show the currently unmatched URL

---

docs/docs/guides/nesting-navigators.md

Improve documentation around nesting navigators
Documentation is not accurate
I test it on test project before submitting the changes
None

Update nesting navigators documentation

---

docs/docs/intro.md
package.json
packages/expo-router/package.json
yarn.lock

bump metro to latest

---

packages/expo-router/src/LocationProvider.tsx
packages/expo-router/src/Route.tsx
packages/expo-router/src/__tests__/getLinkingConfig.test.node.ts
packages/expo-router/src/__tests__/matchers.test.node.ts
packages/expo-router/src/fork/__tests__/getPathFromState-upstream.test.node.ts
packages/expo-router/src/fork/__tests__/getStateFromPath.test.node.ts
packages/expo-router/src/fork/getPathFromState.ts
packages/expo-router/src/fork/getStateFromPath.ts
packages/expo-router/src/getLinkingConfig.ts
packages/expo-router/src/getRoutes.ts
packages/expo-router/src/link/useLinkToPath.ts
packages/expo-router/src/link/useLinkToPathProps.tsx
packages/expo-router/src/matchers.tsx
packages/expo-router/src/views/Sitemap.tsx

Bit easier to draw comparisons when the name is the same across frameworks. Resolve ENG-7169

Rename fragments to groups

---

packages/expo-router/src/fork/__tests__/getStateFromPath-upstream.test.node.ts
packages/expo-router/src/fork/getStateFromPath.ts

- `app/(one)/(two)/index.js` should match `/` 
- resolve ENG-7202

resolve root in nested group

---

packages/expo-router/src/useScreens.tsx

- fix https://github.com/expo/router/issues/192

add listeners prop to Screen

---

docs/docs/features/linking.md
docs/docs/features/routing.md
docs/docs/guides/auth.md
docs/docs/guides/tabs.md
docs/docs/intro.md
docs/docs/migration/react-navigation/custom-navigators.md
docs/docs/migration/react-navigation/screen-tracking.md
docs/docs/migration/react-navigation/screen.md
docs/docs/migration/react-navigation/themes.md

@evanbacon/testing feedback

---

docs/docs/features/errors.md
docs/docs/features/unmatched.md
docs/docs/guides/auth.md
docs/docs/guides/headers.md
docs/docs/guides/index.md
docs/docs/guides/modals.md
docs/docs/migration/react-navigation/custom-navigators.md
docs/docs/migration/react-navigation/link.md
docs/docs/migration/react-navigation/navigating.md
docs/docs/migration/react-navigation/params.md
docs/docs/migration/react-navigation/screen.md
docs/docs/migration/react-navigation/stack.md
docs/docs/migration/react-navigation/use-navigation.md

fix docs problems

---

packages/expo-router/package.json

- fix https://github.com/expo/router/issues/275

add 48 beta support

---

docs/docs/guides/headers.md

Outdated/incorrect info in docs.
N/A
N/A

Typeo/outdated prop name fixes.

---

packages/expo-router/src/LocationProvider.tsx
packages/expo-router/src/__tests__/LocationProvider.test.node.ts
packages/expo-router/src/fork/getPathFromState.ts

Previous implementation was not as robust as already-existing `deepEqual` 
reuse `deepEqual`
Added test

refactor-object-comparison

---

packages/expo-router/CHANGELOG.md
packages/expo-router/package.json
packages/expo-router/src/link/linking.ts

other: make react-native-gesture-handler required

---

docs/docs/features/linking.md

fix highlight next line

---

packages/expo-metro-runtime/src/async-require/fetchThenEval.web.ts

Remove extraneous head injection

---

README.md

Show example of Guest List app with Expo Router
Added a link to the readme
- Check whether the link works
- Check whether the repo is high enough quality

Add Guest List app

---

packages/expo-router/src/fork/getPathFromState.ts

refactor: remove ts-expect-error from getPathFromState

---

packages/expo-metro-runtime/src/location/install.native.ts

fix(runtime): fix production crash

---

packages/expo-router/CHANGELOG.md
packages/expo-router/src/__tests__/loadStaticParamsAsync.test.node.ts
packages/expo-router/src/loadStaticParamsAsync.ts

fix `generateStaticParams` with clone syntax.

---

packages/expo-router/CHANGELOG.md
packages/expo-router/src/views/Screen.tsx
packages/expo-router/src/views/Unmatched.tsx

fix loading useLayoutEffect in non-browser environment.

---

packages/expo-metro-runtime/CHANGELOG.md
packages/expo-metro-runtime/src/location/install.native.ts

- Use all manifest fallbacks from the updates team
- Move process env check before production -- requires production testing.

fix location polyfill in development

---

docs/docs/guides/nesting-navigators.md

Documentation is essential when using this package. If the documentation is not carefully crafted, such as inconsistent spacing, it can confuse the reader.
I fixed the spacing of the example code.
- No test plan.

Beautify the spacing of the code example

---

packages/expo-router/src/fork/getPathFromState.ts
packages/expo-router/src/link/href.ts

Fix: https://github.com/expo/router/issues/550
Fix: https://github.com/expo/router/issues/542

feat: automatically urlencode path params

---

packages/expo-router/src/layouts/Tabs.tsx

I think this comment is stale 😊

Remove stale comment

---

packages/expo-router/src/static/renderStaticContent.tsx

https://github.com/expo/router/discussions/588

fix ssg warning

---

packages/expo-router/src/__tests__/navigation.test.tsx
packages/expo-router/src/global-state/routing.ts

- Make it clearer how to fix https://github.com/expo/router/issues/699

fix(router): improve mounting error message

---

packages/expo-metro-runtime/src/HMRClient.native.ts

Fix native HMRClient.native.ts import

---

packages/expo-router/src/useScreens.tsx

- fix https://github.com/expo/router/issues/710

feat(router): add custom getId

---

packages/expo-router/src/global-state/router-store.tsx
packages/expo-router/src/global-state/routing.ts
packages/expo-router/src/hooks.ts
packages/expo-router/src/imperative-api.ts
packages/expo-router/src/types.ts
packages/expo-router/src/views/Sitemap.tsx
packages/expo-router/src/views/Unmatched.tsx

feat(router): expose canGoBack function on router

---

packages/expo-router/src/__tests__/navigation.test.tsx

- This has been fixed and tested, but a more e2e test will help with stability.
- resolve https://github.com/expo/router/issues/345

added test for 345

---

packages/expo-router/src/hooks.ts

- Couldn't hurt to try this https://github.com/expo/router/issues/288#issuecomment-1590772523
- Should fix https://github.com/expo/router/issues/288

memoize useRouter

---

packages/expo-router/e2e/__tests__/__snapshots__/export.test.ts.snap
packages/expo-router/src/static/html.tsx

- fix https://github.com/expo/router/issues/720

add full expo style reset

---

docs/docs/intro.md

Fixed some spelling mistakes in intro.md

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml

- Related https://github.com/expo/expo/pull/24187

update issue template to notify about the migration

---

packages/expo-router/package.json

Forgot to add `testing-library.ts` to `package.json#files`
https://github.com/expo/router/issues/551#issuecomment-1702522286
Need to publish to test...

feat: add testing-library.ts to npm file

---

packages/expo-router/src/global-state/routing.ts

- pull in fix from https://github.com/expo/expo/pull/24548

backport https://github.com/expo/expo/pull/24548

---

packages/expo-router/src/testing-library/index.tsx
packages/expo-router/src/testing-library/mocks.ts

backport of https://github.com/expo/expo/pull/25110

fix(router): update jest testing-library mocks

---

packages/expo-router/src/__tests__/navigation.test.tsx
packages/expo-router/src/global-state/routing.ts

backport of https://github.com/expo/expo/pull/25111

fix relative hrefs inside groups

---

packages/expo-router/src/LocationProvider.tsx
packages/expo-router/src/__tests__/navigation.test.tsx
packages/expo-router/src/global-state/router-store.tsx
packages/expo-router/src/global-state/routing.ts

Backport https://github.com/expo/expo/pull/25309

fix(router): relative links with index routes

---

packages/expo-head/package.json
packages/expo-metro-runtime/package.json
packages/expo-router/package.json

fix https://github.com/expo/expo/issues/25385

add MIT licenses

---

packages/expo-router/src/global-state/routing.ts

fix(router): fix state.routes.at is not a function

---

README.md

Make the message a bit more clear, until we are able to archive the repo full.
Utilize GFM custom note.
https://github.com/expo/router/tree/%40simek/readme-tweak?tab=readme-ov-file#expo-router

README emphasize repo state
